### PR TITLE
Added CMAKE_BUILD_TYPE property

### PR DESCRIPTION
**Pull request by Bihlerben**
As discussed in oce-dev. Would the CMake experts have a look at it? I am not that familiar with CMake...

### CODE REVIEW

**Comment by QbProg** [comment]
+1 for me, eventually could you rebase and squash the commits before merging?

**Comment by Bihlerben** [comment]
QbProg, can you tell me how to do that? If I rebase and squash the commits in my branch and try to push the result here, git tells me that the tip of my current branch is behind its remove counterpart. Pulling and merging probably is not the right thing to do... so what should I do?

**Comment by tpaviot** [comment]
@Bihlerben you have to add -f (force) when pushing after a rebase:
```
git checkout  review/CMakeBuildTypeOption
git rebase -i master
# do what you want here squash, edit or whatever
git push -f origin review/CMakeBuildTypeOption
```
If you don't succeed, I can do it.

**Comment by Bihlerben** [comment]
Thank you, Thomas. I guess I have succeeded. :-)

**Pull request merged**
