### PR TITLE
RFC : new oce-win-bundle integration

### PR DESCRIPTION
**Pull request by QbProg**
After a lot of issues, I changed the oce-win-bundle structure so it builds only from source.
Basically all the projects build in the same solution as OCE, like it previously was OCE_BUNDLE_SOURCE.
The bundle is automatically used if the "oce-win-bundle" source directory is present. That directory can be a simple extraction of the source files, or a git clone. 
Please test this branch using the qb/new-bundle branch of the oce-win-bundle repository.

In the end I avoided the external-project cmake functionality because is SO unconfortable to work with in MSVC.

I moved all the bundle-specific code out of CMakeLists, except some minor required instructions which are needed to avoid library search.
I also updated the autoinstall feature so it is compatible with MSVC and MINGW, hopefully removing the confusion that generated in the last pull requests.
Mingw should be working too, but I really kindly ask to test MINGW64 and MINGW32 users in their configuration!

Finally, I re-tested all the MSVC configurations (dynamic, static, XP-libraries), and I setup a new train script in QbProg/oce-builder which should compile all the configurations easily.

Thomas, unfortunately this branch makes your appvoyeur scripts outdated :P We can update these when merged.

The bundle is updated too to support new libraries and it builds automatically TBB.

### CODE REVIEW

**Comment by tpaviot** [comment]
Ok, I will check this new bundle on Mingw32. No problem with the appveyor script, I was not satisfied with the previous bundle integration with oce, and I faced many issues.

**Comment by tpaviot** [comment]
@QbProg On my machine, oce-win-bundle path is D:\Devel\oce-win-bundle and oce is D:\oce. With recent changes introduced in this PR, I can't use the path for my oce-win-bundle location. Do I have to copy/paste this folder the the current cmake build path ?

**Comment by tpaviot** [comment]
After I manually set up OCE_USE_BUNDLE and set this value to True, the configuration process fail and complains with missing freetype includes:
<code>
Build 32bit
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.3/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.3/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/CMake/share/cmake-3.3/Modules/FindFreetype.cmake:151 (find_package_handle_standard_args)
  CMakeLists.txt:426 (find_package)


Configuring incomplete, errors occurred!
See also "D:/Devel/oce/cmake-build-with-bundle/CMakeFiles/CMakeOutput.log".
See also "D:/Devel/oce/cmake-build-with-bundle/CMakeFiles/CMakeError.log".
</code>

**Comment by QbProg** [comment]
It has to be inside d:/oce/oce-win-bundle to make it detect automatically
the bundle. No more manual setup. Btw that subdir is added to git ignore so
it does not annoy in the OCE git status

Il giorno mer 9 set 2015 08:25 Thomas Paviot <notifications@github.com> ha
scritto:

**Comment by tpaviot** [comment]
Ok, I got it, thx. I rebased review/appveyor on top of your branch, in order to check your new-bundle. I had to tweak FetchBundle.bat so that it checks out the correct oce-win-bundle branch), see commit 30c2c6014ca2341dec01b4fc2c4b98e337b64be8.

**Comment by tpaviot** [comment]
OK, according to the appveyor build, it works fine on msvc for both Win32/Win64. On MinGW it fails, there's an issue with FreeImage.

**Comment by QbProg** [comment]
With the latest bundle changes I also fixed mingw installation and test build for static libraries (failing anyway in two cases)
I'd like to merge it, if you all agree.

**Pull request merged**
