### PR TITLE
Minor changes to prepare for wrapping to pythonocc-core

### PR DESCRIPTION
**Pull request by lalvarezt**
This are minor changes to prepare for wrapping to pythonocc-core

### CODE REVIEW

**Comment by tpaviot** [comment]
@lalvarezt Changes are minor, true, however they must be explained. Especially, are these changes absolutely required ? what issue do they fix ?

**Comment by tpaviot** [comment]
@lalvarezt Can you please rebase your branch on top of master

**Comment by lalvarezt** [comment]
@tpaviot Fair enough.

In https://github.com/tpaviot/oce/pull/645/files#diff-29a9ed4fdec459c58381f9ccd324c6b5 The ErrorStatus function was missing in the original OCE pull in the .lxx file, but was declared in the .hxx file. Therefore when pythonocc tries to compile and access the function, it is not present.

In https://github.com/tpaviot/oce/pull/645/files#diff-f6782bdc5860f56d14922060f686a1a2 The handle declaration is outside of the #if declaration.

In https://github.com/tpaviot/oce/pull/645/files#diff-e1817144cd28d7e7f967c8c9bf253b15 Function Box should be exported.

In https://github.com/tpaviot/oce/pull/645/files#diff-658d15482ea6ec4d714fcd702fe96b83 The include files are referencing only the #include <Handle_Geom_Curve.hxx> file, and leaving out the proper declaration, i.e., #include <Geom_Curve.hxx> because there are functions in the .lxx that access types only declared in the main Geom_Curve. Also Geom_Curve includes Handle_Geom_Curve.

Is this enough or I've left something out.

**Comment by jf---** [comment]
@tpaviot Travis is green, the changes well motivated...
any reason not to merge?

**Comment by tpaviot** [comment]
@lalvarezt Some of your changes were superseded by #665 

The BRepLib_CheckCurveOnSurface change was committed in 8c7d0d3234ebb35b0dbe18de422f0bd31696b6b8

**Comment by tpaviot** [comment]
Everything was merge into master. Thanks @lalvarezt for your contribution

**Pull request closed without merging**
