### PR TITLE
Make code compileable with MinGw64

### PR DESCRIPTION
**Pull request by Bihlerben**
Change of a few #if directives, otherwise compilation with MinGw64 fails here

### CODE REVIEW

**Comment by thatcadguy** [comment]
+1, just now noticed this was a problem.

**Comment by dbarbier** [comment]
+1

**Comment by Bihlerben** [comment]
Is the message

continuous-integration/appveyor — AppVeyor build failed 

something I have to care for? I am not familiar with that? Or isn't this the reason why my change has not been pulled yet?

Thank you for an answer. :-)

**Comment by dbarbier** [comment]
No need to care about appveyor yet, sorry for the delay.

**Pull request merged**
