### PR TITLE
Prepare release 0.17.1

### PR DESCRIPTION
**Pull request by tpaviot**
After this release, let's move towards occt6.9.0 integration.

### CODE REVIEW

**Comment by thatcadguy** [comment]
+1

**Comment by QbProg** [comment]
+1 , tested on MSVC2015, test passes

**Comment by thatcadguy** [comment]
Don't know how I never noticed but `TEST(OCAFExportTestSuite, testExportNonAscii)` fails on MinGW-w64 (I don't remember this failing on MinGW), but I'm certain this is because of MinGW and not any recent commits though.

**Comment by thatcadguy** [comment]
#600

**Comment by QbProg** [comment]
how do we update the patches after the release? I have some free time the
next days, would like to try to upgrade!

Il giorno gio 31 dic 2015 alle ore 05:46 Jacob Abel <
notifications@github.com> ha scritto:

**Comment by tpaviot** [comment]
@QbProg Don't know how to add recent changes to the patchset. Restart everything from the beginning ?

**Pull request merged**
