### PR TITLE
Patch from setting correct tolerance, this branch causes test to pass in...

### PR DESCRIPTION
**Pull request by rajeeja**
Fixing some tolerance issues, otherwise test in CGM package developed by SIGMA group at ANL failed
Here is the source code to the test case: https://bitbucket.org/fathomteam/cgm/src/42a63a23681debc97ead9bea99b6c3d348dafa79/test/test_occ.cpp?at=master to work.

### CODE REVIEW

**Comment by thatcadguy** [comment]
Related to #507

**Comment by thatcadguy** [comment]
@rajeeja Could you elaborate on the change to BRepBuilderAPI_Collect.cxx and what is happening in this block? As I stated in #507, the other changes look fine.

**Comment by rajeeja** [comment]
@thatcadguy thanks for taking this up again. Scaling a body requires changes to all the underneath topology including SOLID. Example: A brick is created and scaled - it needs updation of SOLID & SHELL & .. VERTEX as here: http://www.opencascade.com/doc/occt-6.9.1/refman/html/_top_abs___shape_enum_8hxx.html#a67b8aa38656811eaee45f9df08499667

This enum is confusing ./inc/TopAbs_ShapeEnum.hxx (vertex=7 is highest and solid=2), usually vertex in lowest. Anyways. The change here BRepBuilderAPI_Collect.cxx says, update SOLID or the calling entity and all the lower dimensional entities. 

Without the change in BRepBuilderAPI_Collect.cxx, a simple test as creating a brick and scaling fails on our CGM repo: CGM test: https://bitbucket.org/fathomteam/cgm/src/1271bd895645a3621bd72834222ed07ef45f9099/test/scale.cpp?fileviewer=file-view-default

I haven't been able to reproduce this inside OCE, because of the way we handle and create entities of lower dimension when creating a brick.

**Comment by thatcadguy** [comment]
@rajeeja Thanks, I understand now. I am +1

**Comment by tpaviot** [comment]
@rajeeja Thank you for this explanation. Working with pythonocc, I noticed a strange behavious with shape scaling. For instance :

* create a sphere with radius 5

* compute the bounding box. You find 10, 10, 10 in bot x,y and z directions

* compute the volume, you find let's say vol1

*  scale the sphere with radius 5 in both x,y and z directions, by a factor 2

* recompute the shape volume. You find, as expected, vol2 = 8*vol1

* but if you recompute the bounding box, it's not 20,20,20. The result given by the bounding box algorithm is not the one expected. In order to get the good resutl, I have to mesh the shape, with a good precision, and pass that mesh to the bounding box algorithm. 

Do you think it's related to the issue you describe ?

If you don't fully understand I can attach a sample code.

**Comment by rajeeja** [comment]
@tpaviot Yes, it should be related. The mesh operation that you mention might be getting rid of all the lower dimension entities and only needing FACE/EDGE/VERTEX as in the current code, causing the computation to succeed. Please share your code, I can test to see if this change fixes your issue.

Building our (CGM, scale.cpp) example mentioned above is easy. Just checkout cgm from bitbucket and configure using --with-oce option. 

The current code always updates FACE, EDGE and VERTEX and doesn't update the entity itself, WIRE or SHELL.  This might be the cause of bounding box computation error that you mention. In CGM, we use lumps underneath our representation for TopoDS_Solid and other shapes, without this change our method for updating OCC entities fail. ftp://ftp.mcs.anl.gov/pub/fathom/cgm-docs/classOCCBody.html#a629c8cb8c340d3b5bbbb57c02b3cb4ec

**Comment by tpaviot** [comment]
@rajeeja Here is a python code snippet showing the issue. It should easily be ported to c++ if you want to test.

```python
from OCC.BRepPrimAPI import BRepPrimAPI_MakeSphere
from OCC.gp import gp_Mat, gp_GTrsf
from OCC.BRepBuilderAPI import BRepBuilderAPI_GTransform
from OCC.Bnd import Bnd_Box
from OCC.BRepBndLib import brepbndlib_Add


def get_sphere(r):
    return BRepPrimAPI_MakeSphere(r).Shape()


def scale_shape(shape, fx, fy, fz):
    scale_trsf = gp_GTrsf()
    t = gp_Mat(fx, 0., 0., 0., fy, 0., 0., 0., fz)
    scale_trsf.SetVectorialPart(t)
    return BRepBuilderAPI_GTransform(shape, scale_trsf).Shape()


def compute_bbox(shape):
    bbox = Bnd_Box()
    brepbndlib_Add(shape, bbox)
    xmin, ymin, zmin, xmax, ymax, zmax = bbox.Get()
    dx = xmax - xmin
    dy = ymax - ymin
    dz = zmax - zmin
    return dx, dy, dz

sp = get_sphere(5.0)
print(compute_bbox(sp))
sp2 = scale_shape(sp, 2., 2., 2.)
print(compute_bbox(sp2))
```

The script outputs
```bash
...>python bbox_scale_issue.py
(10.0000002, 10.0000002, 10.0000002)
(30.000000399999998, 34.64101655137755, 20.0000004)
```
The second line is obviously wrong. After scaling by a factor 2, we expect the bounding box to be(20, 20, 20), but the one returned is larger than expected.

**Comment by rajeeja** [comment]
I get errors trying to build pythonocc core: http://pastebin.com/NxzhTXvy
Is there a brew package?

**Comment by tpaviot** [comment]
pythonocc is built against oce-0.16.1. No brew package, but you can use conda see https://anaconda.org/dlr-sc/pythonocc-core

**Comment by rajeeja** [comment]
With oce-0.16.1 I get this error:
[ 72%] Built target _RWStl
[ 72%] Built target _Resource
[ 72%] Linking CXX shared module Darwin/x86_64-MinSizeRel-64/_STEPCAFControl.so
Undefined symbols for architecture x86_64:
  "MoniTool_DataMapOfShapeTransient::Clear()", referenced from:
      _wrap_STEPCAFControl_Writer__kill_pointed(_object*, _object*) in STEPCAFControlPYTHON_wrap.cxx.o
      _wrap_delete_STEPCAFControl_Writer(_object*, _object*) in STEPCAFControlPYTHON_wrap.cxx.o
  "vtable for XSControl_Reader", referenced from:
      XSControl_Reader::~XSControl_Reader() in STEPCAFControlPYTHON_wrap.cxx.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Darwin/x86_64-MinSizeRel-64/_STEPCAFControl.so] Error 1
make[1]: *** [CMakeFiles/_STEPCAFControl.dir/all] Error 2
make: *** [all] Error 2

**Comment by thatcadguy** [comment]
@rajeeja C++ version (I get the same result as @tpaviot):

```
#include <ostream>
#include <Standard_Real.hxx>
#include <TopoDS_Shape.hxx>
#include <BRepPrimAPI_MakeSphere.hxx>
#include <Bnd_Box.hxx>
#include <BRepBndLib.hxx>
#include <gp_GTrsf.hxx>
#include <gp_Mat.hxx>
#include <BRepBuilderAPI_GTransform.hxx>

int main()
{
	Standard_Real r = 5, xmin, ymin, zmin, xmax, ymax, zmax;

	TopoDS_Shape sp = BRepPrimAPI_MakeSphere(r).Shape();

	Bnd_Box bbox;
	BRepBndLib::Add(sp, bbox);
	bbox.Get(xmin, ymin, zmin, xmax, ymax, zmax);
	std::cout << xmax - xmin << ", " << ymax - ymin << ", " << zmax - zmin << std::endl;

	gp_GTrsf scale_trsf;
	gp_Mat t(2, 0, 0, 0, 2, 0, 0, 0, 2);
	scale_trsf.SetVectorialPart(t);
	TopoDS_Shape sp2 = BRepBuilderAPI_GTransform(sp, scale_trsf).Shape();

	Bnd_Box bbox2;
	BRepBndLib::Add(sp2, bbox2);
	bbox2.Get(xmin, ymin, zmin, xmax, ymax, zmax);
	std::cout << xmax - xmin << ", " << ymax - ymin << ", " << zmax - zmin << std::endl;

	return 0;
}
```
Compile with `-lTKernel -lTKMath -lTKTopAlgo -lTKBRep -lTKPrim`

**Comment by rajeeja** [comment]
@thatcadguy @tpaviot same results here, even with the changes in this PR, so I was wrong saying that this would fix the error in @tpaviot's test program. I tried scaling and box computation with sphere, cylinder and the results are not as expected. 3D Rectangular and 2D circle or rectangular entities result in expected bounding box. The underlying representation of sphere/cylinder CAD OCE objects after scalar transformation might be an issue. I tried visualizing the final resulting objects for all the cases and the scaling seem to work and all outputs look as expected, but the bounding box computation is off - so this error might possibly come from bounding box computation rather than scaling.

**Comment by rajeeja** [comment]
Method: BRepBndLib::Add does faces/edges and vertices. Would adding other entity types solve the issue?

src/BRepBndLib/BRepBndLib.cxx

**Comment by thatcadguy** [comment]
@rajeeja probably, or perhaps it's not doing the job right for faces (haven't looked at the code, just guessing). Created a new issue for this scaling problem: #595.

I am still for merging this PR.

**Comment by tpaviot** [comment]
Well, I can't see which issue/bug this patch actually fixes. @rajeeja Sure you can't contribute a test to check whether or not your patch is required ?

**Comment by rajeeja** [comment]
@tpaviot , I tried to see if I can isolate the bug to OCE, but couldn't. The underlying geometry creation and manipulation in CGM needs this change: https://bitbucket.org/fathomteam/cgm/commits/1271bd895645a3621bd72834222ed07ef45f9099

Simple creation of geometry and scaling didn't seem to crash on OCE standalone.

**Comment by thatcadguy** [comment]
@rajeeja Should we close this then? The changes still make sense, but if they're not needed...

**Comment by rajeeja** [comment]
@thatcadguy the changes are needed, just that I cannot make a test case for OCE to go with it. Merge this change to master and close:)

**Comment by tpaviot** [comment]
@rajeeja That's a convincing argument ;) The changes look good however, let's merge this branch.

**Pull request merged**
