### PR TITLE
691patched

### PR DESCRIPTION
**Pull request by blobfish**
Here is the merge request you requested, but please don't actually merge this yet.

### CODE REVIEW

**Comment by jf---** [comment]
@blobfish  @dbarbier @tpaviot I hope it OK for me to draw attention to this PR 
The tests pass & its builds ok ( well, I've only tested on osx, blobfish is on windows? )...
So what would be the way forward on integration of OCC 6.9.1? 
I think @blobfish has accomplished quite a bit of work here.
Do I understand correctly that the thing blocking progress are the quilt patches to be updated from the changeset this PR presents?

**Comment by blobfish** [comment]
On 11/19/2015 10:00 PM, Jelle Feringa wrote:
> @blobfish  @dbarbier @tpaviot I hope it OK for me to draw attention to this PR 
> The tests pass & its builds ok ( well, I've only tested on osx, blobfish is on windows? )...
> So what would be the way forward on integration of OCC 6.9.1? 
> I think @blobfish has accomplished quite a bit of work here.
> Do I understand correctly that the thing blocking progress are the quilt patches to be updated from the changeset this PR presents?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/tpaviot/oce/pull/583#issuecomment-158265127
> 

I am on linux(kubuntu 15.10).

https://github.com/tpaviot/oce/pull/587

**Comment by thatcadguy** [comment]
-1, this fails compilation on MinGW as there is stray code in OSD_File.cxx, see explanation on your newer PR #587

**Comment by thatcadguy** [comment]
Superseded by #589

**Pull request closed without merging**
