### PR TITLE
691patched 3

### PR DESCRIPTION
**Pull request by blobfish**
still trying to get through the CI build.

### CODE REVIEW

**Comment by thatcadguy** [comment]
#587 #583

**Comment by thatcadguy** [comment]
As stated in #587, I am +1 on this.

**Comment by thatcadguy** [comment]
@tpaviot Can we merge this?

**Comment by jf---** [comment]
@thatcadguy , probably some more work on having this branch built succesfully on TravisCI might be required? It seems that this branch is in a pretty good state ( passes most tests on OSX ), but the build fails due to:

```bash
0.53s$ sudo apt-get install tcl8.5-dev tk8.5-dev libgl2ps-dev libfreeimage-dev libtbb-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libgl2ps-dev
E: Unable to locate package libfreeimage-dev
E: Unable to locate package libtbb-dev
```

**Comment by thatcadguy** [comment]
@jf--- I believe travis tried this before https://github.com/tpaviot/oce/commit/6f5bc33643ae2bad902d59132c22edb973720396 was merged to master, also just noticed this is 24 commits behind master. @blobfish Would you be able to rebase against master? This will not only prepare it to be merged, but trigger another travis build. If not I can create a copy of your 691patched_3 branch.

**Comment by blobfish** [comment]
On 04/25/2016 07:29 PM, Jacob Abel wrote:
> @jf--- I believe travis tried this before https://github.com/tpaviot/oce/commit/6f5bc33643ae2bad902d59132c22edb973720396 was merged to master, also just noticed this is 24 commits behind master. @blobfish Would you be able to rebase against master? This will not only prepare it to be merged, but trigger another travis build. If not I can create a copy of your 691patched_3 branch.
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/tpaviot/oce/pull/589#issuecomment-214562225
> 

Sorry been away.

Go ahead create 691_patched_4 branch and run with it. I don't think any
of these will be merged. TPaviot and QbProg want to continue on with
using patch files.

**Comment by thatcadguy** [comment]
@blobfish No problem, thanks for replying.

Honestly except for odd platforms, OCE's existence is starting to seem unnecessary. I've started reporting most of the more major issues to OCCT directly (things that need to be fixed upstream anyway no point in separate people fixing the same bug separately, things I don't know how to fix, things I don't have time to fix). Others such as Roman Lygin and Istvan Csanady are using OCCT heavily for their commercial applications and have been hammering the OCCT bugtracker with good results. OCCT has been very cooperative and responsive on their bugtracker. 7.0.0 is pretty clean IMO, I've compiled it on Ubuntu with GCC and Clang with no hiccups, and about as many warnings as we get.

If anything, it seems like we should start fresh with 7.0.0 and patch it for MinGW and other platforms as needed. Istvan's application is for the iPad so he's making sure Clang and Apple OSes get good attention on the OCCT front.

**Comment by a-betenev** [comment]
Hello Jacob,

Thank you for positive feedback on OCCT 7!

Regarding compiler warnings, we believe that OCCT 7 should build cleanly 
by all recent versions of GCC, CLang, and VC++.
(The only known warnings are violations of C strict aliasing rules 
generated by some older GCC versions.)
If you observe some warnings in your configuration, I encourage you to 
register an issue for that in OCCT Mantis, indicating compiler version 
and build options.

Best Regards,
Andrey

2016-04-29 23:04, Jacob Abel пишет:

**Pull request merged**
