### PR TITLE
Change source path in install rule to PROJECT_BINARY_DIR

### PR DESCRIPTION
**Pull request by lvk88**
The cmake macro OCCT_CONFIGURE_AND_INSTALL assumes that the
project is called "OCCT", which is not the case for OCE. Therefore,
OCCT_BINARY_DIR is undefined and the install target was not able to
copy files used by this macro. (e.g. custom.sh)

Without this change, make install fails with the following message:

<pre>
CMake Error at cmake_install.cmake:8097 (file):
  file INSTALL cannot find "//custom_gcc_64.install.sh".
</pre>

Tested on Ubuntu 16.04 with cmake 3.5.1

### CODE REVIEW

**Comment by lvk88** [comment]
I see that travis was failing for the clang + pch builds. I committed a fix ( b9a541b ) that detects whether clang is used as a compiler and excludes  the two culprit headers (stdint.h and inttypes.h) from the list of paths that cotire uses to compile the *_prefix.cxx file.

**Comment by lvk88** [comment]
Ah, Travis was not merciful to me this time... The GCC build without PCH timed out unfortunately. 

On my own fork, it passed though ([see here](https://travis-ci.org/lvk88/oce/builds/458435704) )

**Comment by tpaviot** [comment]
@lvk88 thank you

**Comment by lvk88** [comment]
Oh, I see travis is failing again on clang + pch with errors like this:

<pre>
fatal error: file '/usr/include/string.h' has been modified since the
      precompiled header
      '/home/travis/build/tpaviot/oce/cmake-build/src/TKSTEP209/cotire/TKSTEP209_CXX_prefix.hxx.pch'
      was built
</pre>

This is probably because of my changes... sorry! It is weird that it was not failing on my fork. I am checking it again.

**Comment by lvk88** [comment]
Okay, I think I found the reason, but really don't get why it works like this. Basically, there are two different versions of Standard_TypeDef.hxx in the source tree. The two paths are:

<pre>
oce/src/Standard/Standard_TypeDef.hxx
oce/inc/Standard_TypeDef.hxx
</pre>

Now, line 22 is different for these two files. The hxx that is located in the inc folder has:
<pre>
#if(defined(_MSC_VER) && (_MSC_VER < 1800))
...
#define PRIuPTR "u"
...
#endif
</pre>

while the hxx that is located in the src goes like:
<pre>
#if(defined(_MSC_VER) && (_MSC_VER < 1800)) or (defined(__clang__) && (__clang_major__ == 4))
...
#define PRIuPTR "u"
...
#endif
</pre>

This leads to PRIuPTR being defined twice that generates a ton of warnings about double macro definitions and eventually the error appears. Now, the question is why do header files exist twice all around the place?

In any case, I could remove the preprocessor definition on clang, this will make the warnings and errors disappear.

**Comment by lvk88** [comment]
Sorry if I keep spamming the topic... probably it's better if I document what I find. I had a look on what .hxx files differ in the inc/ folder and in the src/ folder and found out the following list:

<pre>
Files ininc/BRepGProp_Gauss.hxx and insrc/BRepGProp_Gauss.hxx differ
Files ininc/BRepLib_CheckCurveOnSurface.hxx and insrc/BRepLib_CheckCurveOnSurface.hxx differ
Files ininc/BRepOffset_Inter2d.hxx and insrc/BRepOffset_Inter2d.hxx differ
Files ininc/HLRAlgo_PolyShellData.hxx and insrc/HLRAlgo_PolyShellData.hxx differ
Files ininc/IntTools.hxx and insrc/IntTools.hxx differ
Files ininc/IntTools_SurfaceRangeSampleMapHasher.hxx and insrc/IntTools_SurfaceRangeSampleMapHasher.hxx differ
Files ininc/NCollection_CellFilter.hxx and insrc/NCollection_CellFilter.hxx differ
Files ininc/NCollection_Vec2.hxx and insrc/NCollection_Vec2.hxx differ
Files ininc/NCollection_Vec3.hxx and insrc/NCollection_Vec3.hxx differ
Files ininc/NCollection_Vec4.hxx and insrc/NCollection_Vec4.hxx differ
Files ininc/ShapeConstruct_ProjectCurveOnSurface.hxx and insrc/ShapeConstruct_ProjectCurveOnSurface.hxx differ
Files ininc/Standard_CLocaleSentry.hxx and insrc/Standard_CLocaleSentry.hxx differ
Files ininc/Standard_TypeDef.hxx and insrc/Standard_TypeDef.hxx differ
</pre>

Standard_TypeDef.hxx is one of them, which causes the clang build to fail then. Does anyone know why OpenCASCADE follows this pattern of duplicated headers? I thought that the comparison that happens when cmake is executed is exactly for this reason, to detect differing files. In any case, I will temporarily fix the clang issue and submit a different pull request.

Should we clean up all the differing files in a separate pull request?

**Comment by a-betenev** [comment]
Hello,

Note that OCCT does not store header files in inc folder in the source 
tree; they are stored in src only.
Folder inc in OCE was filled in the past by the headers mostly generated 
from CDL, with some modifications indeed.
Now this should not be necessary any more I suppose.
If you are using OCCT CMake script (as it seems), then it  will create 
folder inc in the build folder at configuration step, filled by the 
headers either copied from src, or containing stub links to relevant 
files in src.

Besides, can you share your experience of using Cotire-generated PCH on 
Linux -- do they help accelerating the build?
In my experiments in the past I have not seen essential improvements of 
the build time.

Andrey

**Comment by tpaviot** [comment]
@a-betenev In the opencascade-7.2.0 tar.gz official source archive, there actually is a /inc full of thousands of .hxx files, I just checked. So the /inc folder of oce comes from upstream, I didn't change anything.

**Comment by a-betenev** [comment]
Indeed there is an "inc" folder in the official source archive: these 
are copies of headers from "src" collected in one place to facilitate 
the build for people who do not want to use CMake.
However the original source tree of OCCT (see Git repo at 
http://git.dev.opencascade.org/gitweb/?p=occt.git;a=tree) does not 
contain "inc".

**Comment by a-betenev** [comment]
@lvk88: Thanks for sharing your timings, good to know it is useful with 
CLang too

**Comment by lvk88** [comment]
Thanks for the clarification @a-betenev!
@tpaviot : should I then submit a PR where the headers in <pre>inc</pre> and <pre>src</pre> are synchronized? Or is it better to get rid of <pre>inc</pre> completely then?

**Comment by a-betenev** [comment]
Headers located in subfolder "inc" of the source tree are not used by 
OCCT CMake build procedure (it creates folder "inc" in the build folder 
and populates it by copies of or references to headers from src).
Thus unless your build process relies on presence of the "inc" folder in 
the source tree somehow, I would suggest removing it.

**Comment by tpaviot** [comment]
@a-betenev thanks for the information, I didn't know the /inc folder was dedicated to other build systems than cmake. Since oce only relies on cmake, I agree @lvk88 that the /inc folder should be removed, your PR is welcome

**Pull request merged**
