### PR TITLE
691patched 2

### PR DESCRIPTION
**Pull request by blobfish**
starting with 691patched branch, I rebased in all the commits from the master branch post oce0.17 tag. I figured the conflict between master and the original 691patched branch was the occt changes. So I simply did a 'git merge --ours master' into the the 691patched_2 branch. I hate merging master into a feature branch, but I didn't know a better way. Anyway this should merge to master. It compiles and the test results are the same as before.

### CODE REVIEW

**Comment by thatcadguy** [comment]
-1, this fails compilation on MinGW as there is stray code in OSD_File.cxx starting at line 1437. It appears to be an #ifdef block from the previous definition of BuildTemporary and I'm guessing should just be deleted (I haven't looked at OCCT sources).

**Comment by blobfish** [comment]
On 12/16/2015 02:44 PM, Jacob A wrote:
> -1, this fails compilation on MinGW as there is stray code in OSD_File.cxx starting at line 1437. It appears to be an #ifdef block from the previous definition of BuildTemporary and I'm guessing should just be deleted (I haven't looked at OCCT sources).
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/tpaviot/oce/pull/587#issuecomment-165223290
> 

I see what you mean. That appears to be from the 6.9.1 occt release.
they deleted the function body on both sides of #ifdef block.

**Comment by thatcadguy** [comment]
This also fails on MSVC for me using MSBuild:

```
"c:\ocebuild2\OCE.sln" (default target) (1) ->
"c:\ocebuild2\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"c:\ocebuild2\test\OCAFExport_test\OCAFExport_test.vcxproj.metaproj" (default t
arget) (66) ->
"c:\ocebuild2\adm\cmake\TKBin\TKBin.vcxproj.metaproj" (default target) (67) ->
"c:\ocebuild2\adm\cmake\TKCAF\TKCAF.vcxproj.metaproj" (default target) (72) ->
"c:\ocebuild2\adm\cmake\TKService\TKService.vcxproj.metaproj" (default target)
(75) ->
"c:\ocebuild2\adm\cmake\TKService\TKService.vcxproj" (default target) (76) ->
(ClCompile target) ->
  c:\oce-691patched_2\adm\cmake\tkservice\Precompiled.h(7): fatal error C1083:
Cannot open include file: 'Aspect.hxx': No such file or directory [c:\ocebuild2
\adm\cmake\TKService\TKService.vcxproj]
```

I might've missed something when using CMake (only thing I changed was to disable TKService font because I haven't grabbed the oce-win-bundle), but I don't recall this happening when I compiled master with MSBuild a few days ago.

**Comment by thatcadguy** [comment]
After deleting that ifdef block from OSD_File.cxx it compiled fine with MinGW.

Regarding MSVC, guessing that OCCT removed Aspect.hxx as your branch doesn't have it compared to master, so those references will need to be examined/removed:

```

C:\Users\Jake\Documents\GitHub\oce>git grep "<Aspect.hxx>"
drv/Aspect/Aspect.jxx:#include <Aspect.hxx>
src/Aspect/Aspect.cxx:#include <Aspect.hxx>
src/V3d/V3d_View_4.cxx:#include <Aspect.hxx>
src/Visual3d/Visual3d_ViewManager.cxx:#include <Aspect.hxx>

C:\Users\Jake\Documents\GitHub\oce>git grep "\"Aspect.hxx\""
adm/cmake/TKService/Precompiled.h:#include "Aspect.hxx"

C:\Users\Jake\Documents\GitHub\oce>
```

**Comment by thatcadguy** [comment]
After removing the reference to Aspect.hxx from adm/cmake/TKService/Precompiled.h compilation finishes on MSVC.

@blobfish I'm assuming you've already compiled on Linux and it looks like @jf--- tested this on OS X, so provided you remove that ifdef block and remove the references to Aspect.hxx I think I am +1 on this.

**Comment by blobfish** [comment]
On 12/16/2015 04:27 PM, Jacob A wrote:
> After deleting that ifdef block from OSD_File.cxx it compiled fine with MinGW.
> 
> Regarding MSVC, guessing that OCCT removed Aspect.hxx as your branch doesn't have it compared to master, so those references will need to be examined/removed:
> 
> ```
> 
> C:\Users\Jake\Documents\GitHub\oce>git grep "<Aspect.hxx>"
> drv/Aspect/Aspect.jxx:#include <Aspect.hxx>
> src/Aspect/Aspect.cxx:#include <Aspect.hxx>
> src/V3d/V3d_View_4.cxx:#include <Aspect.hxx>
> src/Visual3d/Visual3d_ViewManager.cxx:#include <Aspect.hxx>
> 
> C:\Users\Jake\Documents\GitHub\oce>git grep "\"Aspect.hxx\""
> adm/cmake/TKService/Precompiled.h:#include "Aspect.hxx"
> 
> C:\Users\Jake\Documents\GitHub\oce>
> ```
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/tpaviot/oce/pull/587#issuecomment-165244239
> 

that file doesn't appear to be in the 691 occt release. Can't comment on
anything windows related.

**Comment by blobfish** [comment]
On 12/16/2015 04:45 PM, Jacob A wrote:
> After removing the reference to Aspect.hxx from adm/cmake/TKService/Precompiled.h compilation finishes on MSVC.
> 
> @blobfish I'm assuming you've already compiled on Linux and it looks like @jf--- tested this on OS X, so provided you remove that ifdef block and remove the references to Aspect.hxx I think I am +1 on this.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/tpaviot/oce/pull/587#issuecomment-165251121
> 

yes I have compiled on linux. Can you push the your changes somewhere so
I can just grab them? Then you windows guys won't have to rely on me
making the correct changes. After that, I will make a 'patched 3' branch
and do another merge request to see if it passes Travis CI.

**Comment by thatcadguy** [comment]
https://github.com/thatcadguy/oce/commit/731b697ecdc62b43079f46076304953000cb7fbf

**Comment by thatcadguy** [comment]
Superseded by #589

**Pull request closed without merging**
