### PR TITLE
revert change in HLR inverted flag

### PR DESCRIPTION
**Pull request by 5263**
from 0a768f56848d12b18c41422554f35a40c72b6d02

### CODE REVIEW

**Comment by dbarbier** [comment]
Hello, can you please elaborate?

**Comment by 5263** [comment]
Hello Denis.
I think that commenting out this line created a regression. And by re enabling the line I was able to mitigate the regression. 
See http://tracker.dev.opencascade.org/view.php?id=25813#c39475 (esp. test case hlr-fillet2)
and http://forum.freecadweb.org/viewtopic.php?f=8&t=10448

**Comment by dbarbier** [comment]
Thanks for the pointers, we should be able to add a unit test for this bug.

**Comment by thatcadguy** [comment]
+1 on this, I looked through the forum post, bugtracker entry, and the source file and agree. This improves HLR for the time being and when OCCT does a more extensive fix for HLR functions we can merge that.

**Pull request merged**
